// Generates assets.js (base64 artwork) from every PNG/JPG in assets/logos/.
// The app runs from file:// where fetch() of local files is blocked, so all
// bundled artwork has to be inlined as data-URIs in a script tag.
//
//   npm i jimp        (once per machine)
//   node tools/build-assets.js
//
// Drop a new logo into assets/logos/ and re-run. The file name becomes the
// label in the app's logo pickers ("psa-seal.png" -> "Psa Seal"), so name the
// files the way you want them to read.
const fs = require('fs');
const path = require('path');
const Jimp = require('jimp');

const ROOT = path.join(__dirname, '..');
const SRC = path.join(ROOT, 'assets', 'logos');
const MAX = 800; // px on the long side - plenty for a ~30 mm print, keeps assets.js small

function label(file) {
  return path.basename(file).replace(/\.[^.]+$/, '')
    .replace(/[-_]+/g, ' ')
    .replace(/\b\w/g, function (c) { return c.toUpperCase(); });
}

async function main() {
  const files = fs.readdirSync(SRC).filter(f => /\.(png|jpe?g)$/i.test(f)).sort();
  if (!files.length) throw new Error('No images in ' + SRC);
  const out = [];
  for (const f of files) {
    const img = await Jimp.read(path.join(SRC, f));
    if (Math.max(img.bitmap.width, img.bitmap.height) > MAX) {
      img.scaleToFit(MAX, MAX);
    }
    const buf = await img.getBufferAsync(Jimp.MIME_PNG);
    const key = path.basename(f).replace(/\.[^.]+$/, '').toLowerCase()
      .replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
    out.push({ key, name: label(f), uri: 'data:image/png;base64,' + buf.toString('base64') });
    console.log(key, img.bitmap.width + 'x' + img.bitmap.height, (buf.length / 1024).toFixed(0) + ' KB');
  }
  const body = out.map(o => '  { key: ' + JSON.stringify(o.key) + ', name: ' + JSON.stringify(o.name) +
    ', dataUri: ' + JSON.stringify(o.uri) + ' }').join(',\n');
  const js = '// GENERATED by tools/build-assets.js from assets/logos/ - do not edit by hand.\n' +
    '// Bundled artwork as base64 data-URIs (the app runs from file://, where\n' +
    '// fetch() of local files is blocked).\n' +
    '(function (root, factory) {\n' +
    '  if (typeof module !== \'undefined\' && module.exports) module.exports = factory();\n' +
    '  else root.PSA_ASSETS = factory();\n' +
    '})(typeof self !== \'undefined\' ? self : this, function () {\n' +
    '  return [\n' + body + ',\n  ];\n});\n';
  fs.writeFileSync(path.join(ROOT, 'assets.js'), js);
  console.log('assets.js written,', (js.length / 1024).toFixed(0), 'KB,', out.length, 'image(s)');
}

main().catch(e => { console.error(e); process.exit(1); });
